// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test1', async function() {
    // Test name: Test1
    // Step # | name | target | value
    // 2 | setWindowSize | 1024x768 | 
    await driver.manage().window().setRect({ width: 1024, height: 768 })
    // 1 | open | /Web-Map-Custom-Element/index-mm-mapp.html | 
    await driver.get("http://localhost:8383/Web-Map-Custom-Element/index-mm-mapp.html")
    // 3 | click | css=mm-mapp | 

    {
      const element = await driver.findElement(By.css("mm-mapp"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 6 | doubleClick | css=mm-mapp | 
    {
      const element = await driver.findElement(By.css("mm-mapp"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
  })
})
