export var Options = {
  featureIndexOverlayOption: false,
  announceMovement: false,
  announceScale: { metric: true, imperial: false },
  defaultExtCoor: 'pcrs',
  defaultLocCoor: 'gcrs',
  locale: {
    cmBack: 'Back',
    cmForward: 'Forward',
    cmReload: 'Reload',
    cmToggleControls: 'Toggle Controls',
    cmCopyCoords: 'Copy',
    cmCopyMapML: 'Map',
    cmCopyExtent: 'Extent',
    cmCopyLocation: 'Location',
    cmToggleDebug: 'Toggle Debug Mode',
    cmPasteLayer: 'Paste',
    cmViewSource: 'View Map Source',
    lmZoomToLayer: 'Zoom To Layer',
    lmCopyLayer: 'Copy Layer',
    lmLayerSettings: 'Layer Settings',
    lmRemoveLayer: 'Remove Layer',
    lmZoomToExtent: 'Zoom To Sub-layer',
    lmCopyExtent: 'Copy Sub-layer',
    lmExtentSettings: 'Sub-layer Settings',
    lmRemoveExtent: 'Remove Sub-layer',
    lmStyle: 'Style',
    lcOpacity: 'Opacity',
    btnAttribution: 'Map data attribution',
    btnZoomIn: 'Zoom in',
    btnZoomOut: 'Zoom out',
    btnFullScreen: 'View Fullscreen',
    btnExitFullScreen: 'Exit Fullscreen',
    btnLocTrackOn: 'Show my location - location tracking on',
    btnMyLocTrackOn: 'My current location, shown on map',
    btnLocTrackOff: 'Show my location - location tracking off',
    btnLocTrackLastKnown: 'Show my location - last known location shown',
    btnMyLastKnownLocTrackOn: 'My last known location, shown on map',
    amZoom: 'zoom level',
    amColumn: 'column',
    amRow: 'row',
    amMaxZoom: 'At maximum zoom level, zoom in disabled',
    amMinZoom: 'At minimum zoom level, zoom out disabled',
    amZoomedOut: 'Zoomed out of bounds, returning to',
    amDraggedOut: 'Dragged out of bounds, returning to',
    amEastBound: 'Reached east bound, panning east disabled',
    amWestBound: 'Reached west bound, panning west disabled',
    amNorthBound: 'Reached north bound, panning north disabled',
    amSouthBound: 'Reached south bound, panning south disabled',
    kbdShortcuts: 'Keyboard shortcuts',
    kbdMovement: 'Movement keys',
    kbdFeature: 'Feature navigation keys',
    kbdPanUp: 'Pan up',
    kbdPanDown: 'Pan down',
    kbdPanLeft: 'Pan left',
    kbdPanRight: 'Pan right',
    kbdPanIncrement: 'pan increment',
    kbdZoom: 'Zoom in/out 3 levels',
    kbdFocusMap: 'Focus map',
    kbdFocusControls: 'Focus controls',
    kbdPrevFeature: 'Previous feature',
    kbdNextFeature: 'Next feature',
    dfLayer: 'Layer',
    dfExtent: 'Sub-layer',
    dfPastedLayer: 'Pasted layer',
    dfFeatureCaption: 'Feature',
    popupZoom: 'Zoom to here',
    popupPropName: 'Property name',
    popupPropValue: 'Property value',
    fIndexNoFeatures: 'No features found'
  },
  localeFr: {
    cmBack: 'Retour',
    cmForward: "Vers l'avant",
    cmReload: 'Rechargez',
    cmToggleControls: 'Basculer les contrôles',
    cmCopyCoords: 'Copie',
    cmToggleDebug: 'Basculer le mode de débogage',
    cmCopyMapML: 'Carte',
    cmCopyExtent: 'Étendue',
    cmCopyLocation: 'Localisation',
    cmPasteLayer: 'Coller',
    cmViewSource: 'Voir la source de la carte',
    lmZoomToLayer: 'Zoomer sur la couche',
    lmCopyLayer: 'Copier (la couche)',
    lmLayerSettings: 'Paramètres de la couche',
    lmRemoveLayer: 'Supprimer la couche',
    lmZoomToExtent: 'Zoomer sur la sous-couche',
    lmCopyExtent: 'Copier (la sous-couche)',
    lmExtentSettings: 'Paramètres de la sous-couche',
    lmRemoveExtent: 'Supprimer la sous-couche',
    lmStyle: 'Style',
    lcOpacity: 'Opacité',
    btnZoomIn: 'Zoomer',
    btnZoomOut: 'Dézoomer',
    btnAttribution: 'Attribution des données cartographiques',
    btnFullScreen: 'Affichage plein écran',
    btnExitFullScreen: 'Quitter le plein écran',
    btnLocTrackOn: 'Afficher ma position - suivi de la position activé',
    btnMyLocTrackOn: 'Ma position actuelle, affichée sur la carte',
    btnLocTrackOff: 'Afficher ma position - suivi de la position désactivé',
    btnMyLastKnownLocTrackOn:
      'Ma dernière position connue, indiquée sur la carte',
    btnLocTrackLastKnown:
      'Afficher ma position - dernière position connue affichée',
    amZoom: 'Niveau de zoom',
    amColumn: 'Colonne',
    amRow: 'Rangée',
    amMaxZoom: 'Au niveau de zoom maximal, le zoom avant est désactivé',
    amMinZoom: 'Niveau de zoom minimum, le zoom arrière désactivé',
    amZoomedOut: 'Zoomé en dehors des limites, retour à',
    amDraggedOut: 'Traîné hors des limites, retour à',
    amEastBound: "Atteint la limite est, déplacement ver l'est désactivé",
    amWestBound: "Atteint la limite ouest, déplacement ver l'ouest désactivé",
    amNorthBound: 'Atteint la limite nord, déplacement vers le nord désactivé',
    amSouthBound: 'Atteint la limite sud, déplacement vers le sud désactivé',
    kbdShortcuts: 'Raccourcis clavier',
    kbdMovement: 'Touches de mouvement',
    kbdFeature: 'Touches de navigation dans les éléments géographiques',
    kbdPanUp: 'Panoramique vers le haut',
    kbdPanDown: 'Panoramique en bas',
    kbdPanLeft: 'Panoramique vers la gauche',
    kbdPanRight: 'Panoramique vers la droite',
    kbdPanIncrement: 'Incrémenter le panoramique',
    kbdZoom: 'Zoom avant/arrière 3 niveaux',
    kbdFocusMap: 'Centrer la carte',
    kbdFocusControls: 'Centrer les contrôles',
    kbdPrevFeature: 'Élément géographique précédente',
    kbdNextFeature: 'Élément géographique suivante',
    dfLayer: 'Couche',
    dfExtent: 'Sous-couche',
    dfPastedLayer: 'Couche collée',
    dfFeatureCaption: 'Élément géographique',
    popupZoom: 'Zoomer ici',
    popupPropName: 'Nom de la propriété',
    popupPropValue: 'Valeur de la propriété',
    fIndexNoFeatures: 'Aucun élément géographique trouvé'
  }
};
