export var Options = {
  featureIndexOverlayOption: false,
  announceMovement: false,
  announceScale: {"metric": true, "imperial": false},
  defaultExtCoor: 'pcrs',
  defaultLocCoor: 'gcrs',
  locale: {
    cmBack: "Back",
    cmForward: "Forward",
    cmReload: "Reload",
    cmToggleControls: "Toggle Controls",
    cmCopyCoords: "Copy",
    cmCopyMapML: "Map",
    cmCopyExtent: "Extent",
    cmCopyLocation: "Location",
    cmToggleDebug: "Toggle Debug Mode",
    cmPasteLayer: "Paste",
    cmViewSource: "View Map Source",
    lmZoomToLayer: "Zoom To Layer",
    lmCopyLayer: "Copy Layer",
    lcOpacity: "Opacity",
    btnZoomIn: "Zoom in",
    btnZoomOut: "Zoom out",
    btnFullScreen: "View Fullscreen",
    btnExitFullScreen: "Exit Fullscreen",
    btnLocTrackOn: "Show my location - location tracking on",
    btnMyLocTrackOn: "My current location, shown on map",
    btnLocTrackOff: "Show my location - location tracking off",
    btnLocTrackLastKnown: "Show my location - last known location shown",
    btnMyLastKnownLocTrackOn: "My last known location, shown on map",
    amZoom: "zoom level",
    amColumn: "column",
    amRow: "row",
    amMaxZoom: "At maximum zoom level, zoom in disabled",
    amMinZoom: "At minimum zoom level, zoom out disabled",
    amZoomedOut: "Zoomed out of bounds, returning to",
    amDraggedOut: "Dragged out of bounds, returning to",
    amEastBound: "Reached east bound, panning east disabled",
    amWestBound: "Reached west bound, panning west disabled",
    amNorthBound: "Reached north bound, panning north disabled",
    amSouthBound: "Reached south bound, panning south disabled",
    kbdShortcuts: "Keyboard shortcuts",
    kbdMovement: "Movement keys",
    kbdFeature: "Feature navigation keys",
    kbdPanUp: "Pan up",
    kbdPanDown: "Pan down",
    kbdPanLeft: "Pan left",
    kbdPanRight: "Pan right",
    kbdPanIncrement: "pan increment",
    kbdZoom: "Zoom in/out 3 levels",
    kbdPrevFeature: "Previous feature",
    kbdNextFeature: "Next feature",
    dfLayer: "Layer",
    popupZoom: "Zoom to here",
    dfPastedLayer: "Pasted layer"
  }
};